### ISSUE TITLE
In inference mode _get_num_objects_per_step throws exception

### ISSUE THREAD

**Issue by okuchaiev** [NVIDIA/OpenSeq2Seq#133]
1) Ideally it should not be called if benchmark flag isn't set at all
2) Targets in inference is actual output generated by the model, right now it expects them from dl?

>
WARNING:tensorflow:From /home/okuchaiev/repos/OpenSeq2Seq/open_seq2seq/parts/transformer/beam_search.py:421: calling reduce_logsumexp (from tensorflow.python.ops.math_ops) with keep_dims is deprecated and will be removed in a future version.
Instructions for updating:
keep_dims is deprecated, use keepdims instead
*** Inference Mode. Loss part of graph isn't built.
Traceback (most recent call last):
  File "/home/okuchaiev/repos/OpenSeq2Seq/run.py", line 253, in <module>
    main()
  File "/home/okuchaiev/repos/OpenSeq2Seq/run.py", line 242, in main
    infer_model.compile()
  File "/home/okuchaiev/repos/OpenSeq2Seq/open_seq2seq/models/model.py", line 350, in compile
    for worker_id in range(self.num_gpus)]
  File "/home/okuchaiev/repos/OpenSeq2Seq/open_seq2seq/models/model.py", line 350, in <listcomp>
    for worker_id in range(self.num_gpus)]
  File "/home/okuchaiev/repos/OpenSeq2Seq/open_seq2seq/models/text2text.py", line 223, in _get_num_objects_per_step
    num_tokens += tf.reduce_sum(data_layer.input_tensors['target_tensors'][1])
KeyError: 'target_tensors'

**Comment by Kipok** [comment]
> Ideally it should not be called if benchmark flag isn't set at all

Why? I thought that it would not harm to always do this benchmarking (should not be virtually any perf loss, as far as I can see). And benchmark flag just indicates that we specifically do benchmarking and want to prepare config for that

**Comment by Kipok** [comment]
This is fixed in dev0.4 branch
