### ISSUE TITLE
iter_size does not properly work with sparse gradients

### ISSUE THREAD

**Issue by okuchaiev** [NVIDIA/OpenSeq2Seq#142]
Error:

> *** Building graph in Horovod rank: 0
Traceback (most recent call last):
  File "run.py", line 254, in <module>
    main()
  File "run.py", line 233, in main
    train_model.compile()
  File "/home/okuchaiev/repos/Work/OpenSeq2Seq/open_seq2seq/models/model.py", line 396, in compile
    skip_update_ph=self.skip_update_ph,
  File "/home/okuchaiev/repos/Work/OpenSeq2Seq/open_seq2seq/optimizers/optimizers.py", line 194, in optimize_loss
    expected_shape=grad.shape,
AttributeError: 'IndexedSlices' object has no attribute 'shape'

You can reproduce on dev0.4 with:
`python run.py --config_file=example_configs/text2text/nmt-reversal-RR.py --mode=train_eval`

**Comment by Kipok** [comment]
Fixed in dev0.4 PR 143
