### ISSUE TITLE
error when testing my installation: AttributeError: 'CacheManager' object has no attribute 'location'

### ISSUE THREAD

**Issue by riyijiye** [NVIDIA/OpenSeq2Seq#408]
after installation following general installation instruction, I tried to test it with bash scripts/run_all_tests.sh, which gives below errors,

ImportError: Failed to import test module: utils
Traceback (most recent call last):
  File "/home/yinyan/anaconda3/lib/python3.6/unittest/loader.py", line 462, in _find_test_path
    package = self._get_module_from_name(name)
  File "/home/yinyan/anaconda3/lib/python3.6/unittest/loader.py", line 369, in _get_module_from_name
    __import__(name)
  File "/workspace/yinyan/cnn_seq2seq_work/OpenSeq2Seq/open_seq2seq/utils/__init__.py", line 2, in <module>
    from .funcs import train, infer, evaluate
  File "/workspace/yinyan/cnn_seq2seq_work/OpenSeq2Seq/open_seq2seq/utils/funcs.py", line 18, in <module>
    from open_seq2seq.data import WKTDataLayer
  File "/workspace/yinyan/cnn_seq2seq_work/OpenSeq2Seq/open_seq2seq/data/__init__.py", line 3, in <module>
    from .speech2text.speech2text import Speech2TextDataLayer
  File "/workspace/yinyan/cnn_seq2seq_work/OpenSeq2Seq/open_seq2seq/data/speech2text/speech2text.py", line 12, in <module>
    import librosa
  File "/home/yinyan/anaconda3/lib/python3.6/site-packages/librosa/__init__.py", line 12, in <module>
    from . import core
  File "/home/yinyan/anaconda3/lib/python3.6/site-packages/librosa/core/__init__.py", line 110, in <module>
    from .audio import *  # pylint: disable=wildcard-import
  File "/home/yinyan/anaconda3/lib/python3.6/site-packages/librosa/core/audio.py", line 16, in <module>
    from .. import util
  File "/home/yinyan/anaconda3/lib/python3.6/site-packages/librosa/util/__init__.py", line 67, in <module>
    from .utils import *  # pylint: disable=wildcard-import
  File "/home/yinyan/anaconda3/lib/python3.6/site-packages/librosa/util/utils.py", line 111, in <module>
    def valid_audio(y, mono=True):
  File "/home/yinyan/anaconda3/lib/python3.6/site-packages/librosa/cache.py", line 49, in wrapper
    if self.location is not None and self.level >= level:
AttributeError: 'CacheManager' object has no attribute 'location'

anyone can help? thanks!

**Comment by vsl9** [comment]
What librosa version do you use? Can you please try the latest version (0.6.3)? I've tested 0.6.1, 0.6.2, 0.6.3 with NVIDIA TensorFlow container: all versions work fine.

**Comment by riyijiye** [comment]
the issue was with 0.6.3 and 0.6.2, not sure why, but is ok now with 0.6.1. thanks!

**Comment by David-Levinthal** [comment]
requirements.txt should install the right version..this is a pain  :-)

**Comment by borisgin** [comment]
David,
Can you open issue on Github with more details on which version worked
please? This would help us to track and add corresponding test,
Thanks, Boris

**Comment by David-Levinthal** [comment]
should 408 just be reopened with the comment that version 0.6.1 works and
the current release 0.6.3 does not?

**Comment by borisgin** [comment]
Right, librosa changed API in 0.4.2

**Comment by David-Levinthal** [comment]
so do you need another github issue..or is 408 adequate?
perfectly happy to make another but it seems a duplicate
d

**Comment by vsl9** [comment]
Ok, now I got it. librosa 0.6.3 works fine in NVIDIA TensorFlow container if it was installed with `pip install librosa -U`. This command should update `joblib` as well. But `requirements.txt` contains `joblib==0.11` which was another fix for older librosa versions. And librosa 0.6.3 isn't compatible with joblib 0.11. I've updated joblib and librosa versions in requirements.txt. Thanks for the issue report!

**Comment by David-Levinthal** [comment]
will this work with natively installed environments? ie..not using the
docker images?
d

**Comment by vsl9** [comment]
It should work now. The main problem with previous requirements.txt was that it:
1) installed the latest librosa (0.6.3 and its dependency joblib 0.13.2)
2) uninstalled joblib 0.13.2 and installed required joblib 0.11 (making librosa broken)

**Comment by David-Levinthal** [comment]
thanks..
:-)
