### ISSUE TITLE
ValueError: operands could not be broadcast together with shapes (1,401) (0,)

### ISSUE THREAD

**Issue by mrgloom** [NVIDIA/OpenSeq2Seq#440]
`python run.py --config_file=example_configs/text2speech/tacotron_gst.py --mode=infer --infer_output_file=unused`

```
Traceback (most recent call last):
  File "run.py", line 103, in <module>
    main()
  File "run.py", line 78, in main
    args, base_config, config_module, base_model, hvd, checkpoint)
  File "/data/my_user_data/external_projects/text-to-speech/OpenSeq2Seq/open_seq2seq/utils/utils.py", line 890, in create_model
    model = base_model(params=infer_config, mode=args.mode, hvd=hvd)
  File "/data/my_user_data/external_projects/text-to-speech/OpenSeq2Seq/open_seq2seq/models/text2speech.py", line 215, in __init__
    super(Text2Speech, self).__init__(params, mode=mode, hvd=hvd)
  File "/data/my_user_data/external_projects/text-to-speech/OpenSeq2Seq/open_seq2seq/models/encoder_decoder.py", line 66, in __init__
    super(EncoderDecoderModel, self).__init__(params=params, mode=mode, hvd=hvd)
  File "/data/my_user_data/external_projects/text-to-speech/OpenSeq2Seq/open_seq2seq/models/model.py", line 341, in __init__
    num_workers=self.num_gpus, worker_id=worker_id,
  File "/data/my_user_data/external_projects/text-to-speech/OpenSeq2Seq/open_seq2seq/data/text2speech/text2speech.py", line 226, in __init__
    fmax=self.params.get('fmax', None)
  File "/usr/local/lib/python3.5/dist-packages/librosa/filters.py", line 247, in mel
    lower = -ramps[i] / fdiff[i]
ValueError: operands could not be broadcast together with shapes (1,401) (0,)
```

**Comment by mrgloom** [comment]
Looks like some bug in 
```
librosa.__version__
'0.5.1'
```
On
```
librosa.__version__
'0.6.0' 
```
it works.

Maybe it's worth to add version of librosa in https://github.com/NVIDIA/OpenSeq2Seq/blob/master/requirements.txt
