### ISSUE TITLE
Beam search decoder does not work in mixed precision/float16

### ISSUE THREAD

**Issue by okuchaiev** [NVIDIA/OpenSeq2Seq#52]
Traceback (most recent call last):
  File "/home/okuchaiev/repos/OpenSeq2Seq/run.py", line 226, in <module>
    main()
  File "/home/okuchaiev/repos/OpenSeq2Seq/run.py", line 220, in main
    hvd=hvd)
  File "/home/okuchaiev/repos/OpenSeq2Seq/open_seq2seq/utils/model_builders.py", line 197, in create_encoder_decoder_loss_model
    hvd=hvd,
  File "/home/okuchaiev/repos/OpenSeq2Seq/open_seq2seq/models/seq2seq.py", line 49, in __init__
    hvd=hvd)
  File "/home/okuchaiev/repos/OpenSeq2Seq/open_seq2seq/models/model.py", line 177, in __init__
    gpu_id=gpu_ind,
  File "/home/okuchaiev/repos/OpenSeq2Seq/open_seq2seq/models/seq2seq.py", line 82, in _build_forward_pass_graph
    decoder_output = self.decoder.decode(input_dict=decoder_input)
  File "/home/okuchaiev/repos/OpenSeq2Seq/open_seq2seq/decoders/decoder.py", line 113, in decode
    return self._decode(self._cast_types(input_dict))
  File "/home/okuchaiev/repos/OpenSeq2Seq/open_seq2seq/decoders/rnn_decoders.py", line 449, in _decode
    output_time_major=time_major,
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/contrib/seq2seq/python/ops/decoder.py", line 201, in dynamic_decode
    initial_finished, initial_inputs, initial_state = decoder.initialize()
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/contrib/seq2seq/python/ops/beam_search_decoder.py", line 308, in initialize
    dtype=nest.flatten(self._initial_cell_state)[0].dtype)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/ops/array_ops.py", line 2446, in one_hot
    "dtype parameter {1}".format(on_dtype, dtype))
TypeError: dtype <dtype: 'float32'> of on_value does not match dtype parameter <dtype: 'float16'>

**Comment by okuchaiev** [comment]
fixed
