### ISSUE TITLE
Interactive Inference Example problem in loading model

### ISSUE THREAD

**Issue by NatBrian** [NVIDIA/OpenSeq2Seq#521]
I downloaded the checkpoints for SpeechToText https://drive.google.com/file/d/12CQvNrTvf0cjTsKjbaWWvdaZb7RxWI6X/view and TextToSpeech https://drive.google.com/file/d/1Ddf7nDI2PpgaxvZMm7bd8N_Evk_ExTwg/view

I extract everything and put each checkpoint folder inside infer_S2T and infer_T2S
so, inside infer_S2T folder there are
- checkpoint (folder)
      checkpoint
      model.ckpt-438235.data-00000-of-00001
      model.ckpt-438235.index
      model.ckpt-438235.meta
- config.py 
similarly with infer_T2S
the code is not abe to load the model, how should I fix the checkpoint?

OSError                                   Traceback (most recent call last)
<ipython-input-1-9daf970c2c2b> in <module>
     30     return model, checkpoint
     31 
---> 32 model_S2T, checkpoint_S2T = get_model(args_S2T, "S2T")
     33 model_T2S, checkpoint_T2S = get_model(args_T2S, "T2S")
     34 

<ipython-input-1-9daf970c2c2b> in get_model(args, scope)
     26     with tf.variable_scope(scope):
     27         args, base_config, base_model, config_module = get_base_config(args)
---> 28         checkpoint = check_logdir(args, base_config)
     29         model = create_model(args, base_config, config_module, base_model, None)
     30     return model, checkpoint

D:\GitHub\OpenSeq2Seq\open_seq2seq\utils\utils.py in check_logdir(args, base_config, restore_best_checkpoint)
    692           raise IOError(
    693               "There is no valid TensorFlow checkpoint in the "
--> 694               "{} directory. Can't load model".format(ckpt_dir)
    695           )
    696       else:

OSError: There is no valid TensorFlow checkpoint in the Infer_S2T/ directory. Can't load model

**Comment by fabianoluzbr** [comment]
Hi NatBrian, I'm also having an error to run Interactive Inference, but mine is this:
``
Traceback (most recent call last):
  File "demo_streaming_asr.py", line 22, in <module>
    asr = FrameASR()
  File "/Users/fabiano.luz/Dropbox/AIProjects/ASR/OpenSeq2Seq/frame_asr.py", line 67, in __init__
    self.model_S2T, checkpoint_S2T = self._get_model(model_params, scope_name)
  File "/Users/fabiano.luz/Dropbox/AIProjects/ASR/OpenSeq2Seq/frame_asr.py", line 283, in _get_model
    model = create_model(args, base_config, config_module, base_model, None)
  File "/Users/fabiano.luz/Dropbox/AIProjects/ASR/OpenSeq2Seq/open_seq2seq/utils/utils.py", line 879, in create_model
    model = base_model(params=infer_config, mode=args.mode, hvd=hvd)
  File "/Users/fabiano.luz/Dropbox/AIProjects/ASR/OpenSeq2Seq/open_seq2seq/models/encoder_decoder.py", line 66, in __init__
    super(EncoderDecoderModel, self).__init__(params=params, mode=mode, hvd=hvd)
  File "/Users/fabiano.luz/Dropbox/AIProjects/ASR/OpenSeq2Seq/open_seq2seq/models/model.py", line 341, in __init__
    num_workers=self.num_gpus, worker_id=worker_id,
  File "/Users/fabiano.luz/Dropbox/AIProjects/ASR/OpenSeq2Seq/open_seq2seq/data/speech2text/speech2text.py", line 110, in __init__
    num_workers, worker_id)
  File "/Users/fabiano.luz/Dropbox/AIProjects/ASR/OpenSeq2Seq/open_seq2seq/data/data_layer.py", line 76, in __init__
    check_params(params, self.get_required_params(), self.get_optional_params())
  File "/Users/fabiano.luz/Dropbox/AIProjects/ASR/OpenSeq2Seq/open_seq2seq/utils/utils.py", line 409, in check_params
    raise ValueError("{} parameter has to be specified".format(pm))
ValueError: dataset_files parameter has to be specified
``

Have you had this problem?
